### ISSUE TITLE
cannot install after 0.9.1 is released

### ISSUE THREAD

**Issue by nslynx** [Mord3rca/gamma-launcher#55]
One of the mods cannot be installed

![изображение](https://github.com/Mord3rca/gamma-launcher/assets/5699209/61f9fc3d-53ae-4e53-b6b7-da2a1b1c3078)

**Comment by nslynx** [comment]
By the way, 0.9.1 is too unstable

**Comment by Mord3rca** [comment]
Hello @nslynx , thanks for the bug request.

I've added a fix on [fix_malformed_archive](https://github.com/Mord3rca/gamma-launcher/tree/fix_malformed_archive) branch, can you give it a try ?

Regarding 0.9.1 stability ... I can only suggest to rollback in 0.9.0 by putting GAMMA definition of this version in Grok's mod folder and use: `--no-def-update` when running full install.

WARNING: This is not guaranteed to work since 'old' mods are overwritten and not available on modDB

**Comment by nslynx** [comment]
This bug was fixed
![изображение](https://github.com/Mord3rca/gamma-launcher/assets/5699209/cf53d78d-665a-4748-b753-ac1352fcc5d4)
