### ISSUE TITLE
2 Outdated/Borked Mods Installation & Modded Exe

### ISSUE THREAD

**Issue by Poggesh** [Mord3rca/gamma-launcher#92]
**164- Hunger Thirst Sleep UI 0.71 - xcvb** and **190- Screen Space Shaders 18.0 - Ascii1457** are both outdated, causes the game to crash at start.

Temporary solution;
Manually install the newest [Hunger Thirst Sleep Bar mod](https://www.moddb.com/mods/stalker-anomaly/addons/hunger-thirst-sleepiness-bars) 
Manually reinstall SSS - You don't have to download anything, it should've downloaded the newest one by default. No need to fiddle with the options either, just press Ok. Download [here](https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders/) if needed.

GAMMA's current modded exe that is installed by default (ver 2023.12.24) has a fatal bug, I've reported this to Demonized and he has [fixed](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/releases/tag/2024.01.11) it yesterday.

**Comment by Mord3rca** [comment]
Errors look like an upstream issue

**Comment by stubkan** [comment]
Sorry, I am a noob to using Mod Organizer...  could you explain for me, what does "manually install" mean?

Do I have to unzip the mod file contents into GAMMA/mods/ ? 

The contents of GAMMA/mods/165- Hunger Thirst Sleep UI htsb knifebinoc patches - xcvb does not match the contents of HTS_bars_1.01.zip so I dont see how I can do that.

If I place it into GAMMA/downloads/ then it seems to me, its not really installed yet, because it has not been installed into /mods/

The modded exes are simple enough, I can see that the file structure matches /Anomaly structure so I just unzipped them there, but the mod files, I am unclear on what to do with these

**Comment by soboruco** [comment]
Adding to the solution above, the newest Hunger Thirst Sleep Bar mod seems to place the bars behind the ones from the GAMMA UI. Someone on the GAMMA Discord [posted](https://discord.com/channels/912320241713958912/922555488665743391/1114966915274784919) the original mod which is supposed to download with the launcher. Just use this one instead: [Hunger_thirst_sleep_UI_0.71.zip](https://cdn.discordapp.com/attachments/922555488665743391/1114966915534815372/Hunger_thirst_sleep_UI_0.71.zip)

**Note:** none of the patches are required, only the `00. UI Main` folder is.
