### ISSUE TITLE
Issues with extracted mod archives not exisiting

### ISSUE THREAD

**Issue by nozwock** [Mord3rca/gamma-launcher#98]
For example, in here:
```
[+] Installing mod: High Res PDA Maps
  - Downloading High_Resolution_PDA_Maps.1.zip: 116MiB [00:20, 5.96MiB/s] 
    Installing High Res PDA Maps -> ../files/mods/26- High Res PDA Maps - Bazingarrey
    WARNING: High Res PDA Maps does not exist
```
Here, `pdir` is the tempdir with prefix `gamma-launcher-modinstall-` used for extracting the mod archive, sure, but why is it looking for a dir (presumably) named `High Res PDA Maps`? from `_install_directives`?
https://github.com/Mord3rca/gamma-launcher/blob/38b5de7d087091beac6a24fa1b9f710664ff454d/launcher/mods/base.py#L184-L191
Well, the result is that, the `GAMMA/mods/<mod name>` directory is empty except the meta file, other times with some of the components of the mod missing. There are many such warnings leading to an improper installation.

**Comment by Mord3rca** [comment]
Upstream error, looking for a folder name **High Res PDA Maps** but, since a mod update, the folder is named **High Resolution PDA Maps**

https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_data/modpack_maker_list.txt#L26C1-L26C42

Archive content:
![image](https://github.com/Mord3rca/gamma-launcher/assets/25133280/c81bc613-d75b-4675-8770-a010fc914f74)
